<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-07-24 06:14
=======
# Generated by Django 3.0.8 on 2020-07-23 08:48
>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventsHistory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshistory',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
