# Generated by Django 3.0.8 on 2020-07-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0001_initial'),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.Clubs'),
        ),
    ]
