# Generated by Django 3.0.8 on 2020-07-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0002_auto_20200723_0848'),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubs.Clubs'),
        ),
    ]
