<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-07-23 12:53
=======
# Generated by Django 3.0.8 on 2020-07-23 08:48
>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
