<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-07-23 12:18

from django.conf import settings
=======
# Generated by Django 3.0.8 on 2020-07-23 08:48

>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c
            ],
        ),
        migrations.CreateModel(
            name='ClubUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.Clubs')),
<<<<<<< HEAD
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 4dc920873052c577dd63e80ebe66c9dfd0bea68c
            ],
        ),
    ]
