# Generated by Django 3.0.8 on 2020-07-20 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=4)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('average_hr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calories_burned', models.DecimalField(decimal_places=2, max_digits=4)),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('workout_effectiveness', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
