# Generated by Django 3.0.8 on 2020-07-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'COACH'), (2, 'ATHLETE')], default=2),
        ),
    ]
