# Generated by Django 3.0.8 on 2020-07-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200720_0713'),
        ('user', '0005_auto_20200717_0625'),
        ('user', '0002_auto_20200716_1154'),
    ]

    operations = [
    ]
