# Generated by Django 3.0.8 on 2020-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0),
        ),
    ]
