# Generated by Django 3.0.8 on 2020-07-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_gender'),
        ('user', '0006_merge_20200720_1113'),
    ]

    operations = [
    ]
