# Generated by Django 3.0.8 on 2020-07-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0002_auto_20200722_1202'),
        ('user', '0008_auto_20200722_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='primary_sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary', to='Sports.Sports'),
        ),
        migrations.AddField(
            model_name='users',
            name='secondary_sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary', to='Sports.Sports'),
        ),
    ]
